# Generated by Django 3.2.15 on 2022-09-20 08:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_value', models.FloatField(default=0)),
                ('current_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_value', models.FloatField(default=0)),
                ('current_price', models.FloatField(default=0)),
                ('last_sell_price', models.FloatField(default=0)),
                ('materials', jsonfield.fields.JSONField(default=dict)),
                ('ingredients', models.ManyToManyField(to='product.material')),
                ('share', models.ManyToManyField(to='product.measure')),
            ],
        ),
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(choices=[('doone', 'Doone'), ('geram', 'Geram')], default='geram', max_length=10)),
                ('value', models.FloatField(blank=True, default=0)),
                ('name', models.CharField(max_length=10)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.material')),
            ],
        ),
    ]
