# Generated by Django 3.2.15 on 2022-10-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='kala',
            name='share',
        ),
        migrations.DeleteModel(
            name='calc',
        ),
    ]
