# Generated by Django 3.2.15 on 2022-10-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221010_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kala',
            old_name='current_value',
            new_name='current_value_instorage',
        ),
        migrations.RenameField(
            model_name='kala',
            old_name='last_sell_price',
            new_name='total_value',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='current_value',
            new_name='current_value_instorage',
        ),
        migrations.AddField(
            model_name='kala',
            name='item',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='product.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kala',
            name='price_per_unit',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
