# Generated by Django 3.2.15 on 2022-10-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20221012_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='item',
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(default=0)),
                ('price_per_unit', models.FloatField(default=0)),
                ('impact', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.material')),
            ],
        ),
    ]
