# Generated by Django 3.2.15 on 2022-10-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20221012_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_per_unit',
        ),
    ]
