# Generated by Django 4.1.2 on 2022-10-29 14:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_item_cart_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='measurement',
        ),
        migrations.AlterField(
            model_name='kala',
            name='materials',
            field=jsonfield.fields.JSONField(),
        ),
    ]
