# Generated by Django 4.1.2 on 2022-11-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_user_nid_user_phone_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teded', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.kala')),
            ],
        ),
    ]
