# Generated by Django 4.1.2 on 2022-11-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_material_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcart',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.material'),
        ),
        migrations.AlterField(
            model_name='fcart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fcart',
            name='tedad',
            field=models.IntegerField(default=0),
        ),
    ]
