# Generated by Django 4.1.2 on 2022-11-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_fcart_element_alter_fcart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcart',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.kala'),
        ),
    ]
