# Generated by Django 4.1.2 on 2022-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_fcart_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcart',
            name='tedad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_value_instorage',
            field=models.FloatField(default=0),
        ),
    ]
