# Generated by Django 4.1.2 on 2022-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_fcart_tedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='price_per_unit',
            field=models.IntegerField(blank=True),
        ),
    ]
