# Generated by Django 4.1.2 on 2022-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_material_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='expire_date',
            field=models.DateField(blank=True),
        ),
    ]
