# Generated by Django 4.1.2 on 2022-12-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_material_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='current_value_instorage',
        ),
    ]
