# Generated by Django 4.1.2 on 2022-12-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_kala_current_value_instorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='total_value',
        ),
    ]
