# Generated by Django 4.1.2 on 2022-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_factor_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='active_user',
            field=models.CharField(default='salam', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='fact_type',
            field=models.CharField(default='sal', max_length=10),
            preserve_default=False,
        ),
    ]
