# Generated by Django 4.1.2 on 2022-12-12 09:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_material_all_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='all_dates',
            field=jsonfield.fields.JSONField(),
        ),
    ]
