# Generated by Django 4.1.2 on 2022-12-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_material_all_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcart',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
            preserve_default=False,
        ),
    ]
