# Generated by Django 4.1.2 on 2022-12-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_fcart_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('show', models.BooleanField()),
                ('last_update', models.DateField()),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
