# Generated by Django 4.1.2 on 2022-12-13 17:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='all_values',
            field=jsonfield.fields.JSONField(default=5),
            preserve_default=False,
        ),
    ]
